import type { Athlete } from "./types";

export const ATHLETES: Athlete[] = [
    {
        id: "ibragimova",
        name: "Лейла Ибрагимова",
        role: "Чемпионка Кубка России",
        initials: "ЛИ",
        image: "/images/athletes/leila-ibragimova.jpg",
        achievements: [
            { event: "КАРДО", place: 1, year: 2026, note: "региональный этап" },
            { event: "Кубок федерации Забайкалья", place: 1, year: 2026 },
            { event: "Кубок России в Чите", place: 1, year: 2025 },
        ],
    },
    {
        id: "murzin",
        name: "Владислав Мурзин",
        role: "Призёр края",
        initials: "ВМ",
        image: "/images/athletes/vladislav-murzin.jpg",
        achievements: [
            { event: "«Энергия улиц»", place: 2, year: 2023 },
            { event: "Закрытие летнего сезона", place: 1, year: 2024 },
            { event: "Турнир 9 мая", place: 1, year: 2024 },
            { event: "Внутриклубные", place: 1, year: 2025 },
            { event: "Внутриклубные", place: 1, year: 2026 },
            { event: "Краевые Забайкалья", place: 2, year: 2025 },
            { event: "Отбор на КАРДО", place: 2, year: 2026 },
            { event: "Троеборье", place: 3 },
            { event: "Фристайл", place: 3 },
            { event: "Кубок федерации", place: 3, year: 2024 },
            { event: "«Олимпиец»", place: 3, year: 2026 },
        ],
    },
    {
        id: "likhanov",
        name: "Илья Лиханов",
        role: "Чемпион кубка Федерации",
        initials: "ИЛ",
        image: "/images/athletes/ilia-lihanov.jpg",
        achievements: [
            { event: "Кубок федерации", place: 2, year: 2024 },
            { event: "Городской чемпионат", place: 2, year: 2025 },
            { event: "Краевые Забайкалья", place: 2, year: 2025 },
            { event: "Кубок федерации Забайкалья", place: 1, year: 2025 },
            { event: "Street Energy", place: 1, year: 2026 },
            { event: "Троеборье", place: 1, year: 2026 },
            { event: "«Олимпиец»", place: 2, year: 2026 },
            { event: "Статика", place: 1, year: 2026 },
            { event: "Внутриклубные", place: 1, year: 2025 },
            { event: "Внутриклубные", place: 1, year: 2026 },
        ],
    },
    {
        id: "likhanova",
        name: "Аня Лиханова",
        role: "Призёр Кубка России",
        initials: "АЛ",
        image: "/images/athletes/anna-lihanova.jpg",
        achievements: [
            { event: "КАРДО", place: 3, year: 2025, note: "региональный этап" },
            { event: "Краевые Забайкалья", place: 2, year: 2025 },
            { event: "Кубок России", place: 2, year: 2025 },
            { event: "Кубок федерации", place: 2, year: 2025 },
            { event: "Street Energy", place: 3, year: 2026 },
            { event: "Троеборье", place: 2, year: 2026 },
            { event: "«Олимпиец»", place: 2, year: 2026 },
            { event: "КАРДО", place: 3, year: 2026, note: "региональный этап" },
        ],
    },
    {
        id: "purtov",
        name: "Глеб Пуртов",
        role: "Чемпион троеборья",
        initials: "ГП",
        image: "/images/athletes/gleb-purtov.jpg",
        achievements: [
            { event: "Троеборье", place: 1, year: 2026, note: "12–15, стадион СибВО" },
            { event: "Троеборье", place: 1, year: 2026, note: "парк Ододора" },
        ],
    },
    {
        id: "shilnikov",
        name: "Сергей Шильников",
        role: "Призёр кубка Федерации",
        initials: "СШ",
        image: "/images/athletes/sergei-shilnikov.jpg",
        achievements: [
            { event: "Кубок федерации", place: 3, year: 2025 },
            { event: "Внутриклубные", place: 2, year: 2026, note: "2023–2026, серебро и бронза" },
        ],
    },
    {
        id: "shchelkachev",
        name: "Кирилл Щелкачев",
        role: "Чемпион отбора на КАРДО",
        initials: "КЩ",
        image: "/images/athletes/kirill-shelkachev.jpg",
        achievements: [
            { event: "Отбор на КАРДО", place: 1, year: 2026 },
            { event: "Street Energy", place: 1, year: 2026 },
            { event: "«Вызов улиц»", place: 1, year: 2025 },
            { event: "«Олимпиец»", place: 3, year: 2025 },
            { event: "Кубок России", place: 3, year: 2025 },
        ],
    },
];
