import { ReactNode } from "react";
import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/ui/header/Header";
import Footer from "./components/ui/footer/footer";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

interface RootLayoutProps {
    children: ReactNode;
}

const RootLayout = ({ children }: RootLayoutProps) => {
    return (
        <html lang="ru">
            <head>
                <meta name="robots" content="noindex, nofollow" />
            </head>
            <body>
                <div className="flex flex-col">
                    <Header />
                    <main className="flex-1">{children}</main>
                    <Footer />
                </div>
            </body>
        </html>
    );
};

export default RootLayout;
